services:
  accounts:
    container_name: accounts
    restart: unless-stopped
    build:
      context: .
      target: prod
    image: ${IMAGE_TAG}
    expose:
      - 8000
    volumes:
      - ${LOG_PATH:-./logs}:/logs
      - static_files:/app/static_files
    env_file:
      - .env
    command: uv run gunicorn --bind 0.0.0.0:8000 accounts.wsgi ${APP_RUN_PARAMS:-}
    networks:
      - nginx-proxy

  webserver:
    container_name: accounts-webserver
    restart: unless-stopped
    image: nginx:1.29-alpine
    expose:
      - 80
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - static_files:/app/static_files
    depends_on:
      - accounts
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true

volumes:
  static_files:
